repo = "helix-editor/helix"

remote-branch = "master"

local-branch = "patchy"

pull-requests = [
  # Fix open_{below, above} with multi-cursor
  "12465",
  # Show the primary selection index on statusline
  "12326",
  # File browser
  "11285",
  # Command expansion v2
  "11164",
  # Persistant state
  "9143",
  # :trim to remove trailing whitespace
  "8366",
  # Toggle case commands
  "12043",
  # Fix matching inside/around closest pair inconsistency
  "10611",
  # Subword text object
  "12026",
  # Command history picker
  "8354",
  # Preview scrolling
  # "11441",
]
